# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build And Test CDK Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      home_working_directory: "/home/runner/work/Credibility-Assessment-Framework/Credibility-Assessment-Framework"
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: check env
      run: pwd && ls
    - name: Build with NPM
      run: find . -maxdepth 4 -name package.json -exec sh -c 'for file do dir=${file%/*}; cd $dir; echo $pwd; npm install; cd ${{env.home_working_directory}}; done' sh {} +
    - name: Test all submodules
      run: find . -maxdepth 4 -name package.json -exec sh -c 'for file do dir=${file%/*}; cd $dir; echo $pwd; npm run test; cd ${{env.home_working_directory}}; done' sh {} +

